import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import { library } from "@fortawesome/fontawesome-svg-core";
import { fab } from "@fortawesome/free-brands-svg-icons";
import { far } from "@fortawesome/free-regular-svg-icons";
import { fas } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import Navbar from "./components/mainpage/navbar.vue";
import OptionIncome from "./components/subcomponents/evaluationsub/option-part1/option-income.vue";
import OptionSex from "./components/subcomponents/evaluationsub/option-part1/option-sex.vue";
import OptionStudy from "./components/subcomponents/evaluationsub/option-part1/option-study.vue";
import OptionWorkage from "./components/subcomponents/evaluationsub/option-part1/option-workage.vue";
import OptionPart2 from "./components/subcomponents/evaluationsub/option-part2.vue";
import OptionPart3 from "./components/subcomponents/evaluationsub/option-part3.vue";
import DesEvaFirst from "./components/subcomponents/evaluationsub/description-part1.vue";
import DesEvaSec from "./components/subcomponents/evaluationsub/description-part2.vue";
import DesEvaThird from "./components/subcomponents/evaluationsub/description-part3.vue";
import Option2Part1 from "./components/subcomponents/evaluationsub2/option2-part1.vue";
import Option2Part2 from "./components/subcomponents/evaluationsub2/option2-part2.vue";
import OptionDeath from "./components/subcomponents/evaluationsub2/option-death.vue";
import DesEva2First from "./components/subcomponents/evaluationsub2/description2-part1.vue";
import DesEva2Sec from "./components/subcomponents/evaluationsub2/description2-part2.vue";
library.add(fas);
library.add(far);
library.add(fab);
const app = createApp(App);
app.component("fa", FontAwesomeIcon);
app.component("Nav",Navbar);
app.component("Opbar-income", OptionIncome);
app.component("Opbar-sex", OptionSex);
app.component("Opbar-study", OptionStudy);
app.component("Opbar-workage", OptionWorkage);
app.component("Opbar-2", OptionPart2);
app.component("Opbar-3", OptionPart3);
app.component("Des-1", DesEvaFirst);
app.component("Des-2", DesEvaSec);
app.component("Des-3", DesEvaThird);
app.component("Opbar2-1",Option2Part1);
app.component("Opbar2-2",Option2Part2);
app.component("Opbar-Death",OptionDeath);
app.component("Des2-1",DesEva2First);
app.component("Des2-2",DesEva2Sec);

app.use(router);

app.mount("#app");
